name: Docker Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag $IMAGE_NAME
    - name: Log in to registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin
      if: ${{ github.event_name != 'pull_request' }}
    - name: Push Image
      run: |
        IMAGE_ID=ghcr.io/$IMAGE_NAME
        # Strip git ref prefix from version
        VERSION=$(grep __version__ src/solarmax2mqtt/_version.py | cut -d '"' -f2 | xargs)

        echo IMAGE_ID=$IMAGE_ID
        echo VERSION=$VERSION
        docker tag $IMAGE_NAME $IMAGE_ID:$VERSION
        # TODO: only tag latest if on "main"
        docker tag $IMAGE_NAME $IMAGE_ID:latest
        docker push -a $IMAGE_ID
      if: ${{ github.event_name != 'pull_request' }}
